SELECT P1.PK_PRODUITS, PIS.PUISSANCE_MOTEUR, PIS.LONGUEUR,
  IF (NOT EXISTS (SELECT * FROM LINKS_PRODUITS_TYPES_PILOTES WHERE PK_PRODUITS = P1.PK_PRODUITS AND PK_IX_PRODUITS_TYPES_PILOTES <> 2), 1, 0) CO_NAV_UNIQUEMENT,
  IF (P1.LOCATION_QUAI = 1 AND P1.LOCATION_NAVIGATION = 0, 1, 0) A_QUAI_UNIQUEMENT,
  P1.MOYENNE_EVALUATIONS_GLOBALE MOYENNE_EVALUATIONS_GLOBALES,
  P1.CAPACITE_NAVIGATION CAPACITE_CONSEILLEE,
  C1.TAUX_MOYEN_REPONSE_MESSAGES,
  D1.ZA1 REGION,
  C1.DELAIS_MOYEN_REPONSE_MESSAGES,
  P1.PK_IX_PRODUITS_TYPES TYPE_BATEAU_ID,
  P1.PRIX_HAUTE_SAISON_JOURNEE,
  PIS.ANNEE ANNEE_CONSTRUCTION,
  (SELECT COUNT(*) FROM CONVERSATIONS WHERE PK_PRODUITS = P1.PK_PRODUITS) NB_INTERLOCUTEURS,
  (SELECT COUNT(*) FROM RESERVATIONS WHERE PK_PRODUITS = P1.PK_PRODUITS AND PK_IX_RESERVATIONS_ETATS = 2 AND DATE_SUPPRESSION IS NULL) NB_ACCEPTEE,
  (SELECT COUNT(*) FROM PRODUITS_IMAGES WHERE PK_PRODUITS = P1.PK_PRODUITS) NB_IMAGES, 
  IF((SELECT COUNT(*) FROM COMPTES_IMAGES WHERE PK_COMPTES = C1.PK_COMPTES), 1, 0) PHOTO_PROFIL,
  P1.AFFICHER 
FROM PRODUITS P1 
INNER JOIN COMPTES C1 ON C1.PK_COMPTES = P1.PK_COMPTES 
INNER JOIN PRODUITS_INFORMATIONS_SUPPLEMENTAIRES PIS ON PIS.PK_PRODUITS = P1.PK_PRODUITS 
INNER JOIN FILS_ARIANE D1 ON D1.LNG = P1.LOCALISATION_LNG AND D1.LAT = P1.LOCALISATION_LAT AND D1.PK_IX_LANGAGES = 1 
WHERE P1.DATE_SUPPRESSION IS NULL;



        """
        c = csv.writer(open("C:/Users/Administrateur/Documents/Click&Boat/Thomas/test.csv", "wb"))
        c.writerow(["id", "Score", "COEFF","PUISSANCE_PERSONNE", "TAUX_TRANSFORMATION", "PRIX_PERSONNE",
                    "PRIX_METRE", "PRIX_PUISSANCE", "DELAIS_MOYEN_REPONSE_MESSAGES",
                    "MOYENNE_EVALUATIONS_GLOBALE", "CO_NAV_UNIQUEMENT", "A_QUAI_UNIQUEMENT", "NB_IMAGES",
                    "PHOTO_PROFIL","ANNEE_CONSTRUCTION_AGREGE", "URL"])
        """