SELECT P1.PK_PRODUITS, PIS.PUISSANCE_MOTEUR, PIS.LONGUEUR,
  IF (NOT EXISTS (SELECT * FROM LINKS_PRODUITS_TYPES_PILOTES WHERE PK_PRODUITS = P1.PK_PRODUITS AND PK_IX_PRODUITS_TYPES_PILOTES <> 2), 1, 0) CO_NAV_UNIQUEMENT,
  IF (P1.LOCATION_QUAI = 1 AND P1.LOCATION_NAVIGATION = 0, 1, 0) A_QUAI_UNIQUEMENT,
  P1.MOYENNE_EVALUATIONS_GLOBALE NOTE_MOYENNE,
  C1.TAUX_MOYEN_REPONSE_MESSAGES,
  C1.DELAIS_MOYEN_REPONSE_MESSAGES,
  (SELECT COUNT(*) FROM CONVERSATIONS WHERE PK_PRODUITS = P1.PK_PRODUITS) NB_INTERLOCUTEURS,
  (SELECT COUNT(*) FROM RESERVATIONS WHERE PK_PRODUITS = P1.PK_PRODUITS AND PK_IX_RESERVATIONS_ETATS = 2 AND DATE_SUPPRESSION IS NULL) NB_RESA_ACCEPTEE,
  (SELECT COUNT(*) FROM PRODUITS_IMAGES WHERE PK_PRODUITS = P1.PK_PRODUITS AND DATE_SUPPRESSION IS NULL) NB_PHOTOS,
  IF((SELECT COUNT(*) FROM COMPTES_IMAGES WHERE PK_COMPTES = C1.PK_COMPTES), 1, 0) PHOTO_PROFIL,
  P1.AFFICHER
FROM PRODUITS P1
INNER JOIN COMPTES C1 ON C1.PK_COMPTES = P1.PK_COMPTES
INNER JOIN PRODUITS_INFORMATIONS_SUPPLEMENTAIRES PIS ON PIS.PK_PRODUITS = P1.PK_PRODUITS
WHERE P1.DATE_SUPPRESSION IS NULL;
